language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
- mvn --settings .settings.xml install -P docs -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
- ./docs/src/main/asciidoc/ghpages.sh
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn --settings .settings.xml deploy -nsu -Dmaven.test.redirectTestOutputToFile=true'
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] && mvn --settings .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true'
env:
  global:
  - GIT_NAME="Dave Syer"
  - GIT_EMAIL=dsyer@pivotal.io
  - CI_DEPLOY_USERNAME=buildmaster
  - secure: HwFqZ7eBanb79EYgjSksuVekCC7dDiyxsWvEBmxr6uQaJGhNU8ac9LOeH86GO5xpoEaCG7urJu+eO9E84gRe2Qy5Nwauj9Z4OQOoqBwYA4mE5R4x8eVydzC46rzkghmSffYFY3L3LwpByr9HZNPMcCHczr9dQ8B8No5tBopTLu8=
